### ISSUE TITLE
Great paper, trouble accessing raw data

### ISSUE THREAD

**Issue by benbowen** [AharoniLab/MatchWeiz#2]
We just read your recent [paper](http://www.nature.com/articles/ncomms12423), think its great, and would like to use your library in our experiments and for algorithm validation.  I only skimmed parts of the paper so maybe I overlooked it, but do you have an alternative download for the library spectra?  The link to metabolights (http://www.ebi.ac.uk/metabolights/MTBLS330) isn't currently working.  

If you have the spectra in a less raw form where spectra are associated with compound identifiers that would be ideal (save me the munging headaches).

Great work!

**Comment by AharoniLab** [comment]
Hi and thanks for the feedback and for raising the issue. The Metabolights dataset will be updated shortly and will contain supporting spectra and annotation data related to specific results presented in the paper  (DOI:10.1038/ncomms12423). For academic usage of the library spectra, please contact the corresponding author, Prof. Asaph Aharoni <asaph.aharoni@weizmann.ac.il>

**Comment by benbowen** [comment]
Will do. Thanks for the clarification.

**Comment by andrewrobertjones** [comment]
I just tried to access MTBLS330 at Metabolights and also find the link down. Any update on this?

**Comment by khaug** [comment]
Dear all

I am the project leader for MetaboLights. This study was never completed by the submitter. It fails almost all validation checks we have.  We contacted the submitter, but nothing was done so this study is deemed dormant until the submitter completes the submission.

We can not release the data in the current state.

**Comment by AharoniLab** [comment]
Dear Ken,

Thanks for your update. I would be glad to get some concrete assistance in getting this project on line, as many of the verification errors we got for it were too general to be helpful. However, I believe that the substantial amount of information has been properly submitted, and that most of the problems are taxonomy related.

I am also not aware of any notification regarding this study by the Metabolights team, apart from this massage and our own correspondence over a year ago... in any case - I will try to restart the submission a.s.a.p.

Best,
Nir,
The Aharoni Lab.
________________________________

**Comment by khaug** [comment]
That's great news Nir. Together we can make sure this submission gets through the various validation steps. With the additional information from the paper, we can see what needs doing at this stage.
